### ISSUE TITLE
On linux, the script does not work as documented on the readme

### ISSUE THREAD

**Issue by wiki-me** [lilydjwg/2bbcode#6]
doing :

`./2bbcode -f org <  ../orgModeFile.org`

returns nothing, doing:

`./2bbcode  org <  ../orgModeFile.org`

(removing the "-f")

works as expected (this is pretty obvious if you read the script, it just passes the first argument to the -f flag of pandoc) , 

I think modifying the script to:

`exec pandoc -t "$me"/bbcode.lua "$@"` 

will work better (basically passing all the parameters to pandoc).

**Comment by Keksoj** [comment]
This, absolutely this.

**Comment by lilydjwg** [comment]
I've updated the README.

With regard to the breaking change, I prefer to give it a larger change _someday_, i.e. clean up all these scripts and use a uniform entry script. But in which script? I don't write `bat`s. I don't want to write complex bash scripts either.

**Comment by Keksoj** [comment]
as said about the `2bbcode`script :

> I think modifying the script to:
>     exec pandoc -t "$me"/bbcode.lua "$@"
> will work better (basically passing all the parameters to pandoc).

I performed this change in the bash script and it worked, otherwise I had an error. Now it looks like this:

```shell
#!/bin/bash

format=${1:-markdown_github}
me=$(dirname $(realpath $0))

# exec pandoc -f $format -t "$me"/bbcode.lua

exec pandoc -t "$me"/bbcode.lua "$@
```
